In [2]:
import numpy as np 
from matplotlib import pyplot as plt


lets do a fun expirement lets take two matrices A and B and multiply both then we will both 


In [3]:
A = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
B  = np.array([[9, 8, 7], [6, 5, 4],[3, 2, 1]])
Mult_AB = np.cross(A, B)
print(Mult_AB) # Cross Product of two matrices


[[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]
